export const TEAM_TO_ISO = {
  'Argentina': 'ar',
  'Brasil': 'br',
  'Brazil': 'br',
  'France': 'fr',
  'España': 'es',
  'Spain': 'es',
  'USA': 'us',
  'South-Korea': 'kr',
  'Korea Republic': 'kr',
  'Ivory-Coast': 'ci',
  'Cote d\'Ivoire': 'ci',
  'Germany': 'de',
  'England': 'gb-eng',
  'Portugal': 'pt',
  'Netherlands': 'nl',
  'Uruguay': 'uy',
  'Mexico': 'mx',
  'United States': 'us',
  'Canada': 'ca',
  'Morocco': 'ma',
  'Senegal': 'sn',
  'Japan': 'jp',
  'South Korea': 'kr',
  'Australia': 'au',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'Qatar': 'qa',
  'Ecuador': 'ec',
  'Colombia': 'co',
  'Chile': 'cl',
  'Peru': 'pe',
  'Venezuela': 've',
  'Bolivia': 'bo',
  'Paraguay': 'py',
  'Croatia': 'hr',
  'Serbia': 'rs',
  'Switzerland': 'ch',
  'Belgium': 'be',
  'Poland': 'pl',
  'Denmark': 'dk',
  'Austria': 'at',
  'Scotland': 'gb-sct',
  'Turkey': 'tr',
  'Ukraine': 'ua',
  'Czech Republic': 'cz',
  'Hungary': 'hu',
  'Romania': 'ro',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Greece': 'gr',
  'Albania': 'al',
  'Georgia': 'ge',
  'Egypt': 'eg',
  'Nigeria': 'ng',
  'Cameroon': 'cm',
  'Ghana': 'gh',
  "Ivory Coast": 'ci',
  'Tunisia': 'tn',
  'Algeria': 'dz',
  'Mali': 'ml',
  'Guinea': 'gn',
  'South Africa': 'za',
  'New Zealand': 'nz',
  'Indonesia': 'id',
  'Thailand': 'th',
  'Iraq': 'iq',
  'Jordan': 'jo',
  'Saudi Arabia': 'sa',
  'UAE': 'ae',
  'Costa Rica': 'cr',
  'Panama': 'pa',
  'Honduras': 'hn',
  'El Salvador': 'sv',
  'Guatemala': 'gt',
  'Jamaica': 'jm',
  'Haiti': 'ht',
  'Trinidad and Tobago': 'tt',
  'Wales': 'gb-wls',
  'Italy': 'it',
  'Sweden': 'se',
  'Norway': 'no',
  'Finland': 'fi',
  'Russia': 'ru',
  'Israel': 'il',
  'Iceland': 'is',
  'Bosnia and Herzegovina': 'ba',
  'North Macedonia': 'mk',
  'Montenegro': 'me',
  'Kosovo': 'xk',
  'Uzbekistan': 'uz',
  'China': 'cn',
  'India': 'in',
  'Vietnam': 'vn',
  'Myanmar': 'mm',
  'Syria': 'sy',
  'Lebanon': 'lb',
  'Yemen': 'ye',
  'Oman': 'om',
  'Bahrain': 'bh',
  'Kuwait': 'kw',
  'Palestine': 'ps',
  'Kyrgyzstan': 'kg',
  'Tajikistan': 'tj',
  'Afghanistan': 'af',
  'Tanzania': 'tz',
  'Uganda': 'ug',
  'Zimbabwe': 'zw',
  'Mozambique': 'mz',
  'Ethiopia': 'et',
  'Kenya': 'ke',
  'Zambia': 'zm',
  'Angola': 'ao',
  'Congo DR': 'cd',
  'Gabon': 'ga',
  'Libya': 'ly',
  'Sudan': 'sd',
  'Somalia': 'so',
  'Cabo Verde': 'cv',
  'Liberia': 'lr',
  'Sierra Leone': 'sl',
  'Burkina Faso': 'bf',
  'Niger': 'ne',
  'Mauritania': 'mr',
  'Benin': 'bj',
  'Togo': 'tg',
  'Rwanda': 'rw',
  'Comoros': 'km',
  'Madagascar': 'mg',
  'Malawi': 'mw',
  'Namibia': 'na',
  'Botswana': 'bw',
  'Eswatini': 'sz',
  'Lesotho': 'ls',
  'Papua New Guinea': 'pg',
  'Fiji': 'fj',
  'Solomon Islands': 'sb',
  'Vanuatu': 'vu',
  'Samoa': 'ws',
  'Cuba': 'cu',
  'Dominican Republic': 'do',
  'Belize': 'bz',
  'Nicaragua': 'ni',
  'Curacao': 'cw',
  'Suriname': 'sr',
  'Guyana': 'gy',
};

export const TEAM_TO_SPANISH = {
  'Argentina': 'Argentina',
  'Brasil': 'Brasil',
  'Brazil': 'Brasil',
  'France': 'Francia',
  'España': 'España',
  'Spain': 'España',
  'USA': 'Estados Unidos',
  'South-Korea': 'Corea del Sur',
  'Korea Republic': 'Corea del Sur',
  'Ivory-Coast': 'Costa de Marfil',
  "Cote d'Ivoire": 'Costa de Marfil',
  'Germany': 'Alemania',
  'England': 'Inglaterra',
  'Portugal': 'Portugal',
  'Netherlands': 'Países Bajos',
  'Uruguay': 'Uruguay',
  'Mexico': 'México',
  'United States': 'Estados Unidos',
  'Canada': 'Canadá',
  'Morocco': 'Marruecos',
  'Senegal': 'Senegal',
  'Japan': 'Japón',
  'South Korea': 'Corea del Sur',
  'Australia': 'Australia',
  'Saudi Arabia': 'Arabia Saudita',
  'Iran': 'Irán',
  'Qatar': 'Qatar',
  'Ecuador': 'Ecuador',
  'Colombia': 'Colombia',
  'Chile': 'Chile',
  'Peru': 'Perú',
  'Venezuela': 'Venezuela',
  'Bolivia': 'Bolivia',
  'Paraguay': 'Paraguay',
  'Croatia': 'Croacia',
  'Serbia': 'Serbia',
  'Switzerland': 'Suiza',
  'Belgium': 'Bélgica',
  'Poland': 'Polonia',
  'Denmark': 'Dinamarca',
  'Austria': 'Austria',
  'Scotland': 'Escocia',
  'Turkey': 'Turquía',
  'Ukraine': 'Ucrania',
  'Czech Republic': 'Rep. Checa',
  'Hungary': 'Hungría',
  'Romania': 'Rumania',
  'Slovakia': 'Eslovaquia',
  'Slovenia': 'Eslovenia',
  'Greece': 'Grecia',
  'Albania': 'Albania',
  'Georgia': 'Georgia',
  'Egypt': 'Egipto',
  'Nigeria': 'Nigeria',
  'Cameroon': 'Camerún',
  'Ghana': 'Ghana',
  "Ivory Coast": 'Costa de Marfil',
  'Tunisia': 'Túnez',
  'Algeria': 'Argelia',
  'Mali': 'Mali',
  'Guinea': 'Guinea',
  'South Africa': 'Sudáfrica',
  'New Zealand': 'Nueva Zelanda',
  'Indonesia': 'Indonesia',
  'Iraq': 'Irak',
  'Jordan': 'Jordania',
  'UAE': 'Emiratos Árabes',
  'Costa Rica': 'Costa Rica',
  'Panama': 'Panamá',
  'Honduras': 'Honduras',
  'El Salvador': 'El Salvador',
  'Guatemala': 'Guatemala',
  'Jamaica': 'Jamaica',
  'Wales': 'Gales',
  'Italy': 'Italia',
  'Sweden': 'Suecia',
  'Norway': 'Noruega',
  'Finland': 'Finlandia',
  'Israel': 'Israel',
  'Iceland': 'Islandia',
  'Bosnia and Herzegovina': 'Bosnia y Herz.',
  'North Macedonia': 'Macedonia del Norte',
  'Montenegro': 'Montenegro',
  'China': 'China',
  'India': 'India',
  'Vietnam': 'Vietnam',
  'Syria': 'Siria',
  'Lebanon': 'Líbano',
  'Oman': 'Omán',
  'Bahrain': 'Bahréin',
  'Kuwait': 'Kuwait',
  'Palestine': 'Palestina',
  'Tanzania': 'Tanzania',
  'Uganda': 'Uganda',
  'Zimbabwe': 'Zimbabue',
  'Ethiopia': 'Etiopía',
  'Kenya': 'Kenia',
  'Zambia': 'Zambia',
  'Angola': 'Angola',
  'Congo DR': 'R. D. del Congo',
  'Libya': 'Libia',
  'Sudan': 'Sudán',
  'Cabo Verde': 'Cabo Verde',
  'Burkina Faso': 'Burkina Faso',
  'Niger': 'Níger',
  'Benin': 'Benín',
  'Togo': 'Togo',
  'Rwanda': 'Ruanda',
  'Madagascar': 'Madagascar',
  'Namibia': 'Namibia',
  'Botswana': 'Botsuana',
  'Papua New Guinea': 'Papúa Nueva Guinea',
  'Fiji': 'Fiyi',
  'Solomon Islands': 'Islas Salomón',
  'Samoa': 'Samoa',
  'Cuba': 'Cuba',
  'Dominican Republic': 'Rep. Dominicana',
  'Nicaragua': 'Nicaragua',
  'Suriname': 'Surinam',
  'Guyana': 'Guyana',
};

export function getIsoCode(name) {
  return TEAM_TO_ISO[name] ?? 'un';
}

export function getSpanishName(name) {
  return TEAM_TO_SPANISH[name] ?? name;
}

export const WC2026_GROUPS = {
  A: ['United States', 'España', 'Morocco', 'Japan'],
  B: ['Mexico', 'Germany', 'Nigeria', 'South Korea'],
  C: ['Canada', 'France', 'Senegal', 'Australia'],
  D: ['Argentina', 'Portugal', 'Cameroon', 'Jordan'],
  E: ['Brasil', 'Belgium', 'Tunisia', 'Iraq'],
  F: ['England', 'Netherlands', 'Ghana', 'Ecuador'],
  G: ['Uruguay', 'Croatia', 'Ivory Coast', 'Saudi Arabia'],
  H: ['Colombia', 'Poland', 'Egypt', 'New Zealand'],
  I: ['Venezuela', 'Switzerland', 'Algeria', 'Iran'],
  J: ['Chile', 'Denmark', 'Serbia', 'Costa Rica'],
  K: ['Panama', 'Austria', 'Mali', 'Honduras'],
  L: ['El Salvador', 'Scotland', 'Turkey', 'Guatemala'],
};

export function getTeamGroup(teamName) {
  for (const [group, teams] of Object.entries(WC2026_GROUPS)) {
    if (teams.includes(teamName)) return group;
  }
  return null;
}

export const ALL_WC2026_TEAMS = Object.values(WC2026_GROUPS).flat();
